#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 14 23:45:41 KST 2024
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=Nostalgia_v5.0.zip
